### ISSUE TITLE
Yarn build fails due to missing file

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#2]
while doing yarn & yarn build:
Error: ENOENT: no such file or directory, chmod 'dist/static/config/update-resolv-conf'
    at Object.chmodSync (fs.js:1171:3)
    at /Users/z/dev/mysterium-vpn-desktop/webpack.config.js:84:10

**Comment by cvl** [comment]
cc: @tadaskay

**Comment by chompomonim** [comment]
Very strange. What yarn version do you use? 

```
$ yarn --version
1.21.1
```

```
$ yarn && yarn build

yarn install v1.21.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.41s.
yarn run v1.21.1
$ webpack -p
(node:10224) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

...

[540] ./src/index.tsx + 48 modules 742 KiB {0} [built]
      | ./src/index.tsx 1.21 KiB [built]
      | ./src/utils/paths.ts 555 bytes [built]
      | ./src/supervisor/supervisor.ts 2.18 KiB [built]
      | ./src/main-window.tsx 1.94 KiB [built]
      | ./src/utils/on-process-exit.ts 686 bytes [built]
      | ./src/tray/tray.ts 769 bytes [built]
      | ./assets/fonts/Roboto-Light.ttf 59 bytes [built]
      | ./assets/fonts/Roboto-Medium.ttf 59 bytes [built]
      | ./assets/logo.svg 59 bytes [built]
      | ./src/daemon/store.ts 5.62 KiB [built]
      | ./src/store.ts 1.19 KiB [built]
      | ./src/config.ts 226 bytes [built]
      | ./src/ui-kit/typography.ts 413 bytes [built]
      | ./src/app.tsx 1.15 KiB [built]
      | ./src/tray/quit.ts 700 bytes [built]
      |     + 34 hidden modules
    + 526 hidden modules
✨  Done in 11.04s.
```

**Comment by cvl** [comment]
Works now!
